language: php

services:
  - memcached

before_script:
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
  - composer self-update
  - composer install --dev --prefer-source

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

script:
  - bin/phpunit
