language: php
sudo: false
php:
  - 7.1
  - 7.2
matrix:
  fast_finish: true
services:
  - memcached
before_script:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
before_install:
  - composer self-update --no-progress --no-interaction
install:
  - make deps
script:
  - make test
